# 2025 NFL Midseason Report — content, verbatim from Adam.
# conf drives the accent color on the rank numeral (afc = crimson, nfc = navy).

TEAMS = [
(1, "Seattle Seahawks", "7-2", "nfc", """Seattle is the league’s most complete team through ten weeks, and it hasn’t been particularly close. In a season with questions abound for some of the perennial top contenders, the Seahawks have risen significantly above middling preseason expectations to claim the midseason ranking’s top spot. QB Sam Darnold has been on fire in his new home, boasting the league’s highest QBR and showing strong command of the offense all while protecting the football. Young WR Jaxon Smith-Njigba is a legitimate threat to break Calvin Johnson’s all-time receiving yards record, and has been simply unstoppable this season. The defense is all world, and has absolutely stifled opposing offenses all season, even with a few injuries throughout the course of the year. It will be an exciting finish in the league’s best division to end the year, but Seattle looks like a true contender."""),

(2, "Los Angeles Rams", "7-2", "nfc", """The other top contender in the NFC West is Sean McVay’s Rams. The Rams are the only other NFL team with no real questions or weaknesses, and they play a true complementary brand of football. The ageless QB Matthew Stafford is quietly having an MVP season, and is leaning on the elite tandem of WRs Puka Nacua and Davante Adams en route to the league-lead for touchdown passes. The offense has been unstoppable lately, and the defense, which looked to be LA’s calling card at the season’s outset, has been as advertised. The opportunistic defense has been making the most of their takeaways, and boasts the league’s fourth-ranked differential in that category. The road to the Super Bowl will go through the NFC West this season, as Seattle and Los Angeles are head and shoulders above the rest of the league at the midpoint."""),

(3, "New England Patriots", "8-2", "afc", """The more things change, the more things stay the same. After a half-decade stretch residing in the basement of the AFC, Patriot fans have returned to a land of familiarity at the top of their conference. Strength of scheduling notwithstanding, the Patriots have been soundly defeating the teams in front of them, making up a catalog of wins that includes other contenders in Tampa Bay and Buffalo. HC Mike Vrabel looks like the frontrunner for Coach of the Year, as he has brought the Patriots back to the forefront of the league behind the explosive emergence of second-year signal caller QB Drake Maye. Maye is currently the favorite to win MVP, but the less eye-catching reason for New England’s success is the defense. The Patriots boast the league’s second best scoring defense and have been nothing short of elite against the run."""),

(4, "Detroit Lions", "6-3", "nfc", """Things look a little different in Detroit this year following the departures of Ben Johnson and Aaron Glenn. Make no mistake though, this team is still elite on both sides of the ball, and when both units are clicking they look unbeatable. QB Jared Goff remains the most effective game manager in football, but that is no knock against his skillset. The explosive playmakers surrounding him make his job much easier, as WR Amon-Ra St. Brown and RB Jahmyr Gibbs are All-Pro level players who play in an effective system and behind an elite offensive line. The defense is fantastic as well when healthy, and the return of EDGE Aidan Hutchinson has bolstered a unit that looked lost towards the tail end of last year’s campaign. Minus a few hiccups thus far, the Lions look poised to once again win the NFC North and it will be up to Dan Campbell to get one of the NFL’s best rosters over the hump."""),

(5, "Indianapolis Colts", "8-2", "afc", """Yep, Colts at #5, just like we all predicted during the offseason. This season’s most surprising turnaround has taken the league by storm, and HC Shane Steichen has his squad primed to make a deep postseason run. Obviously, QB Daniel Jones has been surgical this year and currently leads the league in passing yards. We all knew that was going to happen. Right? Jokes aside, Jones has struggled a bit over the last few weeks but overall has been historically effective through the air for Indy. It doesn’t hurt that he has RB Jonathan Taylor next to him either, who has a legitimate chance to win MVP. 14 touchdowns and 1400 all-purpose yards through 10 games speaks for itself. Add in trade deadline acquisition CB Sauce Gardner for the Colts, and the sky is the limit for Indy this year."""),

(6, "Philadelphia Eagles", "6-2", "nfc", """Philly finished last season with one of the most dominant three-month stretch of football we’ve seen in recent memory en route to the franchise’s second Lombardi Trophy. The reigning, defending Super Bowl champs are still elite, make no mistake about it, but there are certainly questions about the Eagles through eight weeks of football. The offense has seemingly taken a pretty substantial step backwards, with the air attack and the run game not living up to the historical highs of last season. The defense is still strong, but it seems as though the departures of DT Milton Williams and EDGE Josh Sweat were a bit more impactful than initially projected. Luckily for Birds fans, Howie Roseman is still the best GM in football and there are rookies waiting in the wings looking to make the jump to stardom on the defensive side of the ball. Philly may not be an overwhelming favorite to repeat this year, but they will still easily cruise to the division title. The first NFC East repeat champion in two decades!"""),

(7, "Kansas City Chiefs", "5-4", "afc", """This team is significantly better than their record states, and I think anyone who has watched football over the last decade would agree with that claim. Take away the season-opening losses to the Chargers and Ravens, who faced a Chief team riddled by injury and suspension, and the recent loss to the Buffalo Bills, and Kansas City would undoubtedly sit at the top of the list. I’m not putting much stake in those losses though, as Buffalo surely knows, it is not the games in October that matter when it comes to Kansas City. QB Patrick Mahomes is playing at a level we haven’t seen from the future Hall of Famer in a few years, and DC Steve Spagnuolo’s unit remains exotic and effective. Picking against the Chiefs to make it to the Super Bowl is like losing money at this point, so expect the Chiefs to climb this list as the season draws to a close."""),

(8, "Buffalo Bills", "6-3", "afc", """What a strange season in Buffalo. It has been hard to get a read on the league’s top contenders from year’s past this season, and Buffalo remains one of the most apparent enigmas through the halfway point. They beat the Chiefs in a thriller one week, then get decimated the next by an atrocious Miami team. QB Josh Allen is still fantastic, but the lack of support around him is starting to catch up, and Allen can’t do it all by himself every week. The defense has also taken a significant step back which puts even more pressure on the offense. It will be up to HC Sean McDermott to guide his team over the hump and past the rival Chiefs come January, or else Bills fans will likely be asking for some sort of large-scale structural change."""),

(9, "Green Bay Packers", "5-2-1", "nfc", """Green Bay started the year off looking like 17-0 was not out of the question, after walloping the Lions and Commanders to start the season. Newly acquired EDGE Micah Parsons and QB Jordan Love looked like they were about to take over the league, and the rest of the NFL was officially on notice. Since week 2 though, Green Bay has cooled off pretty considerably. The Packers have seemingly been stricken with the oft-maligned syndrome of playing down to the level of their opponents. In the NFL though, winning football is winning football, and their record speaks for itself. If HC Matt LaFleur can clean some things up, Green Bay should make the postseason and compete into January. Look to their Week 10 matchup with Philadelphia as a true litmus test for both squads."""),

(10, "Tampa Bay Buccaneers", "6-3", "nfc", """The early season darling Tampa Bay Buccaneers are another potential contender who have cooled off in recent weeks. QB Baker Mayfield began the year playing at an MVP-caliber level, but has regressed slightly from his early season highs, although he has still been playing well with a significantly depleted cast around him. Plenty is still going right down south, and the Bucs have a relatively straightforward path to their sixth-straight division title and a playoff berth. This is still a complete football team, and if Mayfield can get back to playing his hard-nosed brand of football and limiting the turnovers, Tampa Bay will be a force to be reckoned with in the postseason. Rookie WR Emeka Egbuka looks like the clear frontrunner for the Offensive Rookie of the Year Award, the latest in a long line of Ohio State products who have turned heads at the pro level immediately. Mayfield and his Bucs will cruise to the division title by season’s end."""),

(11, "Los Angeles Chargers", "7-3", "afc", """The Chargers, who started the season off with a bang, have been tricky to get a read on. QB Justin Herbert is a true franchise guy, and has been seeing more success this season by using his athleticism to pick up key first downs and keep his unit out on the field. The Bolts boast one of the league’s elite defenses, as HC Jim Harbaugh’s mentality centers around a hard-nosed defensive unit and a tendency to want to punch you in the mouth running the ball on offense. The Chargers play in a very difficult division, but should be able to sneak into a Wild Card spot in a conference that is relatively weak outside of their own backyard."""),

(12, "Denver Broncos", "8-2", "afc", """Who are the Denver Broncos? That is a question that will certainly be answered in the coming weeks, as Sean Payton’s team looks to ride one of the league’s best defenses into postseason glory. There are no questions on that side of the ball, as EDGE Nik Bonitto and CB Patrick Surtain II are two of the most impactful players in the entire NFL, and the entire unit is about as staunch as it gets against both the run and the pass. The questions for Denver lie on offense, as second year QB Bo Nix has taken a pretty noticeable step back this season. He looks unsure of himself and more reluctant to use his athleticism to make plays, often holding the ball for too long and forcing Denver into difficult conversion scenarios. If Nix can right the ship, Denver should be contending deep into the postseason."""),

(13, "Chicago Bears", "6-3", "nfc", """Has it finally happened? Have the Bears finally found a quarterback? Through 10 weeks, it certainly appears so. After a rocky start to this year’s campaign, second year QB Caleb Williams looks to be what was promised to Bears fans last year when they selected the USC product with the #1 overall pick in 2024’s draft. The evolution of Caleb Williams is a testament to how much coaching matters for a young quarterback, and now that HC Ben Johnson has taken the reins in the Windy City, the sky appears to be the limit for the Bears. The offense has been fantastic in recent weeks, driven by Williams’ ability to activate the clutch gene and put the team on his back when the stakes are the highest. It may not be Chicago’s year this season with the gauntlet they play in, but the upward trajectory is clear."""),

(14, "Baltimore Ravens", "4-5", "afc", """1-5 who? Baltimore has seemingly shrugged off an atrocious, injury-marred start to the year by winning three straight. Luckily for the Ravens, they keep getting healthier, and the other members of the AFC North are looking worse and worse week over week. The biggest injection into this team has been the return of QB Lamar Jackson, who when healthy makes a case year in and year out to be the league’s best player. RB Derrick Henry is starting to slow down, as the future Hall of Famer has eclipsed the 30-year old mark and it is now more imperative than ever that Lamar needs to be truly Lamarvelous. The defense also received a shot in the arm with the return of All Pro safety Kyle Hamilton, and this team looks to be trending at the right time."""),

(15, "San Francisco 49ers", "6-3", "nfc", """Tough to get a read on the Niners this year. Yet again, San Francisco has been bitten hard by the injury bug, and it warrants the conversation at this point if the team needs a significant overhaul in terms of the training staff department. Backup QB Mac Jones has filled in admirably this year for Brock Purdy, but at this point, the injuries feel like too much to overcome. The loss of LB Fred Warner really cripples the spirit of this team, and although RB Christian McCaffrey has been playing at an elite level this year, there is simply too much competition within the division and the conference to predict a playoff appearance for San Francisco."""),

(16, "Pittsburgh Steelers", "5-4", "afc", """Another year in Pittsburgh, and another 9-8 season seems inevitable. QB Aaron Rodgers looked like he had finally found the correct dosage of psychedelics to perform at his 2021 level earlier in the year, but it appears that age has finally caught up to the legendary signal caller. The offense has been decent, but the real problem for Pittsburgh lies on defense. When you’re spending that much money on defense, you need a unit that gets it done, and Pittsburgh’s D has been pretty sub-par through 10 weeks. Factor in the resurgence of the Ravens and a few new faces in the AFC playoff picture, and Pittsburgh is in real danger of missing the playoffs after a hot start to the season."""),

(17, "Houston Texans", "4-5", "afc", """Once you hit the back half of the power rankings, team quality seems to tank. Despite the parity in the league being at an all-time high, win-loss records have been pretty lopsided this season, with only a handful of teams hovering around the .500 mark. Houston is one of these teams, and they have started looking better lately after their 0-3 start. The strength of the Texans lies on defense, where they boast the strongest unit in the NFL statistically. The problem for Houston is the continued regression of QB CJ Stroud and the inability of the offense to move the ball efficiently and convert scoring chances into points. Even worse for their outlook, backup QB Davis Mills filled in for Stroud last week, and Houston had their best offensive performance of the season. Not ideal vibes in HTX."""),

(18, "Jacksonville Jaguars", "5-4", "afc", """Jacksonville started the year off burning hot, riding a historically opportunistic defense to victories by capitalizing off turnovers. Things have slowed down in a big way lately, and the biggest culprit behind the team’s lack of success is QB Trevor Lawrence. Lawrence has never grown into the elite quarterback that was promised to Jags fans 5 years ago, and his performance throughout his career is holding the team back. Regardless of how hot the defense was at the beginning of the year, that style of winning football games was never going to be sustainable, and the offense needed to explode in terms of productivity to give fans any semblance of stability for the rest of the year. That production has been nowhere to be seen, and the Jags look like a team that will finish around .500 and miss the postseason."""),

(19, "Atlanta Falcons", "3-6", "nfc", """Disappointing, to say the least for Falcons fans. In what was supposed to be a breakout year for QB Michael Penix Jr, the team has yet to find an identity on offense. This team is much better than their record states, but 3-6 is 3-6. The offense should be extremely explosive on paper, but they haven’t been able to string success along for longer than four quarters. RB Bijan Robinson is probably the most electric player playing on Sundays, but the play calling and lack of offensive rhythm is not doing him justice and severely knee-capping his potential. The defense has surprisingly been elite, with the fourth best EPA against so far this season, but the team has been unable to play complementary football and the Win-Loss column reflects that."""),

(20, "Dallas Cowboys", "3-4-1", "nfc", """If the offense isn’t breaking records, this team simply has no chance to win. With defensive statistics trailing only the free falling Cincinnati Bengals, there is very little hope that Dallas has any chance to make the postseason this year or in the future. The old adage holds true, and defense not only wins championships but also wins games at this level (see: Denver Broncos), and with the offense falling back to earth in recent weeks, things are looking bleak in Jerryworld. The offseason gamble to deal all-world EDGE Micah Parsons to Green Bay has resulted in the second-worst defense in pro football, and GM/Owner Jerry Jones is finally looking like he is in over his head after a legendary tenure helming America’s Team. QB Dak Prescott has been fantastic this season, pairing especially well with the addition of WR George Pickens. RB Javonte Williams has been excellent as well, but the Cowboys stand no chance without a defense."""),

(21, "Carolina Panthers", "5-5", "nfc", """We will have to see how the rest of this season shakes out for Carolina. If things continue to go south, as they have been lately, the front office will need to take a long, hard look at the investment they’ve made in continuing to develop QB Bryce Young. I’m a fan of the Alabama product because he seems like an exemplary individual and a great hang, but at this point, it seems like he does not have what it takes to be a winning starting quarterback in this league. This year has been particularly disappointing for Young because of the strides Carolina has made on defense. After being the worst unit in football a year ago, their defense has figured things out a bit and looks like the only thing they are missing in Charlotte is a quarterback. Unless Young can pull a rabbit out a hat to finish the season and sneak into a Wild Card spot, it is likely the end of the road for the former #1 overall pick."""),

(22, "Minnesota Vikings", "4-5", "nfc", """The Vikings have taken an expected step back this season behind the helm of QB JJ McCarthy. McCarthy, who was Minnesota’s first round pick last year, did not play in 2024, so significant growing pains were to be expected. There is reason to be hopeful in Minnesota, as fans can likely count on HC Kevin O’Connell, one of the league’s best, to be able to mold McCarthy into a winning QB. The defense has been middling, and key departures on that side of the ball have made the Vikings too reliant on heroics from what is essentially a rookie quarterback. More troubling, All Pro WR Justin Jefferson has had his least productive season yet and has been a virtual no-show in games where McCarthy starts. It will be a few years before Minnesota finds themselves relevant again, and that is contingent on the development of their second-year signal caller."""),

(23, "Arizona Cardinals", "3-6", "nfc", """The Arizona Cardinals seem to have finally moved on from QB Kyler Murray. With the insertion of veteran QB Jacoby Brissett proving to be a better move for the team, and the inability of Murray to really establish any sort of stability in his career outside of a stellar rookie season, it appears a new day is dawning in Phoenix. The team has been a dumpster fire this season, losing multiple winnable games and getting blown out in others. The season is over at the midway point for an Arizona team that some thought may be a dark horse contender, but moving on from Murray is the right move and will allow for Arizona’s front office to develop a different young quarterback for their imminent rebuild."""),

(24, "Cincinnati Bengals", "3-6", "afc", """The season was over pretty much as soon as it started, with star QB Joe Burrow going down in Week 2 with yet another catastrophic injury. Veteran QB Joe Flacco has filled in admirably in Burrow’s stead, but even the heroics of a 41-year old aberration cannot make up for the disaster that is the Bengals’ defense. The NFL’s worst defensive unit is pretty much ranked 32nd in every meaningful category, and it continues a worrisome trend over the last few years that despite the firepower on offense, Cincinnati will never be a real contender unless they address the gaping holes on defense. Burrow may return this season, but it doesn’t seem like a move that would make sense given how far outside the playoff picture they look. It appears the Super Bowl appearance hangover continues, and it is high time the Bengals move on from HC Zac Taylor."""),

(25, "Miami Dolphins", "3-7", "afc", """An absolutely pitiful start to the season has been unsuccessfully mitigated by the Dolphins, continuing to play losing football even with the increased quality of play from QB Tua Tagovailoa. HC Mike McDaniel’s tenure appears to be over, despite a confounding, dominant win over the Bills recently. The departure of key defensive fixtures have identified the Dolphins as sellers moving into the offseason, and it appears as a full overhaul is in the works for Miami. Lone bright spot RB De’Von Achane has been terrific this season, and could be an attractive trade target if the Dolphins do decide to clean house. That 70-30 win over the Broncos a few years ago seems further away than the Fins’ last Super Bowl appearance (1985)."""),

(26, "Cleveland Browns", "2-7", "afc", """As miserable as the offense has been this season, there does seem to be hope in Cleveland. The defense is the strong point of this team, and a strong point it certainly is, ranking top 5 in every meaningful defensive statistic. EDGE Myles Garrett continues on his Hall of Fame trajectory, providing a spark for a defense that plays fast and rallies to the ball better than most units in the league. Unfortunately, the elite status of the defense is not enough to win football games when the offense is so historically anemic, and there are no clear answers at the quarterback position. Both QB selections in the 2024 draft for Cleveland appear to be whiffs, with QB Dillon Gabriel getting handed the reins after the departure of QB Joe Flacco to Cincinnati, and playing poorly, as is to be expected. The only hope for Cleveland’s offense is to somehow hit a home run in the 2027 draft, which should be loaded with quarterback talent."""),

(27, "Washington Commanders", "3-7", "nfc", """Oof. What a fall from grace for the NFC runner ups. Washington has been mauled by injury this year, but even that fact should not take away from the fact that the product on the field in the nation’s capital right now is historically awful. Reigning Offensive Rookie of the Year QB Jayden Daniels has spent most of this year on the sideline, and another grotesque injury in Week 8 against Seattle should end his season. Washington’s front office simply put too much faith in the rookie, and refused to fill any of the roster’s needs with young, developmental prospects and instead opted for bringing in even more talent that was great in 2018, but old and ineffective in 2025. HC Dan Quinn should be fired at season’s end, as the current stretch of Commanders football is one of the worst in history, with blow out losses (21+) in four straight games, good for the worst mark since the 2002 Cardinals."""),

(28, "Las Vegas Raiders", "2-7", "afc", """The offseason dice roll that the Raiders made for veteran QB Geno Smith has not paid off. Smith has been one of the league’s worst quarterbacks, and the success of the team has followed suit. Not much to be said for Vegas outside of the encouraging rookie year of RB Ashton Jeanty and the continued dominance of EDGE Maxx Crosby. Jeanty has been effective, but a rookie running back cannot solely provide the spark needed to consistently win NFL football games. TE Brock Bowers is still elite, but his season has been limited with injuries. Until they invest a high draft pick in an elite quarterback prospect, the Raiders will continue to be the bottom-feeders of the meat grinder that is the AFC West."""),

(29, "New York Giants", "2-8", "nfc", """Hope has arrived in New Jersey! Although, in typical Giant fashion, that hope was ripped from the waiting hands of fans as soon as it appeared. The Giants’ 2025 draft class looked excellent early, as the combination of RB Cam Skattebo and QB Jaxson Dart is going to be electric for years to come. Unfortunately, Skattebo suffered a season-ending leg injury and Dart is out indefinitely following a concussion last week. Luckily, #3 overall pickup EDGE Abdul Carter is playing as advertised, and helps support an elite defensive front alongside veterans DT Dexter Lawrence, EDGE Brian Burns, and EDGE Kayvon Thibodeaux. This year is not the Giants’ year, clearly, but there is hope on the horizon for the G-Men."""),

(30, "New Orleans Saints", "2-8", "nfc", """A tough outlook in the offseason for New Orleans has amounted to a 2-8 mark at the midpoint of the season. QB Spencer Rattler was serviceable through the first nine games, but the lack of winning paved the way for second round pick QB Tyler Shough to take over the starting role. Shough is 1-0 in his career, and led the Saints to victory last week against the Panthers. One feel-good win aside, the Saints are a rebuilding team that will not see success in the next 3 years. The defense has holes, the offense is inexperienced, and the coaching staff has been largely ineffective. Another year at the bottom of the NFC South for the Saints."""),

(31, "New York Jets", "2-7", "afc", """Too many expectations in year one for new HC Aaron Glenn. The Jets are coming off back to back wins after starting the season 0-7, but the problems that have plagued the franchise for years now have not been assuaged by Glenn’s arrival. QB Justin Fields has been terrible, but with the nagging injuries to WR Garrett Wilson and RB Breece Hall, the blame does not fall entirely on him. The biggest story with the Jets is that they have officially entered total shut down mode after dealing CB Sauce Gardner and DT Quinnen Williams at the deadline, arguably the team’s two best players. We will see if the move for hoarding draft picks pays off for the Jets, but for now, they remain in the basement of the NFL."""),

(32, "Tennessee Titans", "1-8", "afc", """A tough start to the beginning of QB Cam Ward’s career in 2025. The #1 overall pick has shown a number of flashes this season, but without any sort of support around him, the fact that they have a single win this year is probably something good to build on. The Titans are inept organizationally, and are awful on both sides of the ball. Ward is relatively innocent, as a terrible defense that can’t stop a nose bleed and a geriatric supporting cast on offense do not make a strong developmental foundation for a young quarterback. There are basically no positives this season for Tennessee, and they will likely finish the year 1-16 with the #1 overall pick in next year’s draft."""),
]

# Two picks per award, in the order Adam listed them.
AWARDS = [
("NFL MVP", ("QB", "Drake Maye", "New England Patriots"), ("QB", "Sam Darnold", "Seattle Seahawks")),
("Offensive Player of the Year", ("RB", "Jonathan Taylor", "Indianapolis Colts"), ("WR", "Jaxon Smith-Njigba", "Seattle Seahawks")),
("Defensive Player of the Year", ("EDGE", "Myles Garrett", "Cleveland Browns"), ("EDGE", "Nik Bonitto", "Denver Broncos")),
("Offensive Rookie of the Year", ("WR", "Emeka Egbuka", "Tampa Bay Buccaneers"), ("QB", "Jaxson Dart", "New York Giants")),
("Defensive Rookie of the Year", ("EDGE", "Abdul Carter", "New York Giants"), ("LB", "Jihaad Campbell", "Philadelphia Eagles")),
("Comeback Player of the Year", ("QB", "Daniel Jones", "Indianapolis Colts"), ("RB", "Christian McCaffrey", "San Francisco 49ers")),
("Coach of the Year", ("", "Mike Vrabel", "New England Patriots"), ("", "Shane Steichen", "Indianapolis Colts")),
]
