# 2026-2027 NFL Preseason Report — content verbatim from Adam.

LEDE = """As the colors of the leaves begin to change and the suffocating heat and smoke of our Pacific Northwest summer finally start to abate, the sports-minded of us begin to turn our attention once again to our television sets. After a long and arduous offseason, the Football Gods have finally again blessed our homes and our hearts with a primetime matchup between two league heavyweights in a rematch of last season&rsquo;s championship bout. Tonight, the NFL season begins, but I invite you to take a look with me at the larger picture of the league as a whole. Without further ado, I present to you the 2026-2027 NFL Preseason Report/Prediction."""

DIVISIONS = [
("afc", "North", [
(1, "Cincinnati Bengals", "6-11", "DE Boye Mafe", """Have the Bengals become the new Cowboys? Despite missing out on postseason festivities each year since 2022, the Who Dey faithful remain stalwart in their optimism season in and season out. Is it the Bengal&rsquo;s year? Maybe. The here and now may be the best they&rsquo;ve looked in the preseason since 2022, as there are few questions about their elite offense and ability to produce fireworks. QB Joe Burrow returns from a nasty turf toe injury that sidelined him for a significant portion of 2025, and WR&rsquo;s Ja&rsquo;Marr Chase and Tee Higgins look to capitalize on playing a full campaign with their generational signal caller. The main reason for the Bengals success this season will come from plugging defensive holes with the additions of DT Dexter Lawrence, DT Jonathan Allen, and DE Boye Mafe."""),
(2, "Baltimore Ravens", "8-9", "WR Ja&rsquo;Kobi Lane (R)", """There are a lot of question marks surrounding the Ravens this season as we head into 2026. Most notably, a changing of the guard has occurred in the Head Coach&rsquo;s seat, with former Chargers defensive coordinator Jesse Minter taking the reins from the long-tenured John Harbaugh, who has sought greener pastures in the Meadowlands. Baltimore&rsquo;s success has always been predicated upon their power run game, and the main offensive question is whether or not all-world QB Lamar Jackson will be able to return to MVP form. Defensively, the backfield returns All-Pro safety Kyle Hamilton, whose 2025 campaign was unfortunately marred by injury, and the unit as a whole should be significantly improved from last year with Minter calling the shots."""),
(3, "Pittsburgh Steelers", "10-7", "WR Germie Bernard (R)", """The Mike Tomlin Experience has finally come to a conclusion in the Steel City, after 19 seasons straight finishing above .500. Lack of postseason success led the Steelers front office to pursue someone who they believe can finally get the job done in January, so they hired&hellip;wait, Mike McCarthy? Huh. Anyway, McCarthy gets a reunion with his long-lost QB Aaron Rodgers, the ageless wonder who has committed to this year being his farewell tour. He will be supported by WR D.K. Metcalf, RB Jaylen Warren, and TE Pat Freiermuth. Key additions to the offensive squad include last year&rsquo;s breakout star RB Rico Dowdle and WR Michael Pittman Jr. Pittsburgh looks to rebound defensively from a campaign that saw them ranked towards the basement of the league last season and have added much-needed depth in the box and secondary, headlined by the acquisitions of CB Jalen Ramsey and S Jaquan Brisker."""),
(4, "Cleveland Browns", "5-12", "RB Quinshon Judkins", """Yeah, probably not much of a surprise here. Believeland enters 2026 in quarterback purgatory yet again, as new HC Todd Monken has chosen to delegate offensive responsibilities to All-Around Great Guy and Teammate QB Deshaun Watson. Much to the chagrin of Browns&rsquo; fans, who I would imagine would&rsquo;ve liked to see the nod given to mercurial second-year signal caller QB Shedeur Sanders. Regardless of who is running the offense, firepower remains low, although young bright spots RB Quinshon Judkins and TE Harold Fannin Jr should be able to get Cleveland on the scoreboard with some sense of semi-regularity. Defense, historically the Browns&rsquo; calling card, suffered a massive offseason blow with the departure of Canton-bound DE Myles Garrett, but the unit as a whole should still be serviceable. DE Jared Verse, LB Carson Schwesinger, and CB Denzel Ward will lead this squad to a top 15 ranking in DVOA by season&rsquo;s end, even if the team wins five games or less."""),
]),
("afc", "East", [
(1, "Buffalo Bills", "12-5", "DT Deone Walker", """A bounce back season for the Bills seems to be in order. After another absolute postseason heartbreaker at the hands of Sean Payton, Buffalo has finally made a significant change by ousting HC Sean McDermott (one of the winningest bosses in franchise history), and replacing him with former offensive coordinator Joe Brady. The offense has added playmaking WR DJ Moore from Chicago, and Buffalo boasts one of the best QB/RB duos in the league with QB Josh Allen and RB James Cook. The defense remains largely the same, (although the introduction of a 3-4 scheme to the unit should shake things up somewhat) but the addition of DE Bradley Chubb should help out DE Gregory Rousseau, and a pass rush that was ranked 27th in PRWR in 2025."""),
(2, "New England Patriots", "14-3", "WR Kyle Williams", """After using the genie in the bottle that team owner Robert Kraft found in a Foxborough storage closet back in the year 2000 to wish for multiple Super Bowl trophies and the greatest football player of all time, it seems Kraft has used the genie again to wish for a return to glory. With one of the quickest rebuilds in league history culminating in a Super Bowl appearance last year, New England is one of the most exciting and surprising clubs in football. How long did we have, maybe five years of Patriot irrelevance? QB Drake Maye returns from an MVP-caliber campaign in 2025 and should be much improved behind a better offensive line and the addition of WR AJ Brown. The defense, stalwart in 2025, adds key pieces to the mix in DT Milton Williams and S Kevin Byard III. This year is New England&rsquo;s opportunity to quell the suspicion that the main reason for their success last season was their schedule."""),
(3, "New York Jets", "3-14", "TE Kenyon Sahdiq (R)", """Yep, that&rsquo;s right, you&rsquo;re reading this correctly. The J-E-T-S will not be in the cellar of the AFC East this season! HC Aaron Glenn begins year two in Gotham after a disastrous 2025 campaign, but will take over defensive playcalling duties for a unit that should improve over last year with the addition of journeyman S Minkah Fitzpatrick. On offense, the Jets return former first-round QB Geno Smith, who looks to improve on a 2025 season in Vegas where he led the league in interceptions. WR Garrett Wilson returns from injury, and new Oregon product TE Kenyon Sahdiq should be an immediate difference maker for the other team from New York."""),
(4, "Miami Dolphins", "7-10", "QB Malik Willis", """The Miami Dolphins should end the 2026 season with the only real stat that matters in this league: the first overall draft pick and the right to draft future Hall of Famer WR Jeremiah Smith (Yeah, I&rsquo;m calling it now. Have you seen that dude play?). Looking more immediately, Miami should be an absolute dumpster fire this year, as the team has virtually no bright spots outside of RB De&rsquo;Von Achane. I honestly don&rsquo;t really have a lot to say about this club, aside from that if your favorite team plays against the Dolphins this year, congrats on the win. Look for Miami to win anywhere between one and three games this season."""),
]),
("afc", "South", [
(1, "Houston Texans", "12-5", "G Keylan Rutledge", """After beginning the 2025 season with a record of 0-3, Houston ended up winning a playoff game. QB CJ Stroud should likely improve this season, as further regression seems impossible after a dazzling rookie season followed by two years of sub-par play. It seems like it really can&rsquo;t get worse for Houston offensively than what it looked like in Denver in the playoffs last year, where Stroud was clearly seeing ghosts. Luckily for the Texans, they really only need their offense to score two touchdowns a game, and maybe a field goal, in order to win 12-14 games in 2026. Houston boasts, statistically speaking, one of the best defensive units to play football this century. An embarrassment of riches blesses the Texans across all positions, highlighted by the DE tandem of Will Anderson Jr and Danielle Hunter (27 sacks in 2025(!)), and the secondary pairing of CB Derek Stingley Jr and S Jalen Pitre. If Houston&rsquo;s offense can simply be middle of the road in 2026, this team has a real shot at a title."""),
(2, "Jacksonville Jaguars", "13-4", "RB Bhayshul Tuten", """The Jaguars, one of the NFL&rsquo;s most improved teams last year, are coming in hot off the tail of an AFC South division title and a 13-win season. After losing a heartbreaker to Buffalo in the playoffs, Jacksonville looks to replicate last year&rsquo;s regular season success with a more balanced offensive attack (Enter RB Chris Rodriguez Jr to complement young emergent talent RB Bhayshul Tuten), and finally look for QB Trevor Lawrence to play at an elite level for an entire season. Lawrence was great at times last year, but for Jacksonville to finally get over the hump they need an MVP-caliber season from the Clemson product."""),
(3, "Indianapolis Colts", "8-9", "WR Alec Pierce", """I foresee the Indianapolis Colts having another season similar to 2025, albeit without the red-hot start they experienced behind the excellent play of QB Daniel Jones and the ridiculous first half of the season from RB Jonathan Taylor. The Colts&rsquo; season fell off the rails after Indiana Jones&rsquo; injury, and the team was unable to really get anything going after the midway point. The main question mark with Indianapolis this year is their receiving corps, which following the departure of WR Michael Pittman Jr to Pittsburgh lacks any sort of significant firepower. Jones will look to WR Alec Pierce as his number one target, who is an unquestioned deep threat but we haven&rsquo;t seen Pierce in a number one role before. The defense is largely unchanged and will likely be a middle-of-the-road unit."""),
(4, "Tennessee Titans", "3-14", "WR Wan&rsquo;Dale Robinson", """I have a lot of hope for the Titans this season, I just think the AFC South is going to be too competitive in 2026 for a team that is still clearly rebuilding to throw any sort of wrench into things. Second year QB Cam Ward will take a massive leap forward due to the additions of first-round WR Carnell Tate, who dazzled at Ohio State last season, and WR Wan&rsquo;Dale Robinson, who is sneaky underrated and will be a PPR monster for fantasy owners this year as Tate acclimatizes to the speed of the pro game. Tennessee&rsquo;s defense was surprisingly stout over the first half of the year before regressing to finish with a 28th-overall ranking. DT Jeffrey Simmons is still an elite playmaker and will anchor a defense that will likely improve somewhat."""),
]),
("afc", "West", [
(1, "Denver Broncos", "14-3", "WR Pat Bryant", """It is certainly no steaming hot take to ascertain that, barring the injury to QB Bo Nix at the end of a divisional playoff game last year, Denver almost would&rsquo;ve certainly beat New England in the AFC Championship and advanced to face Seattle in the Super Bowl. However, that was then, and this is now, and Nix looks to be fully healthy and ready to shoulder the burden of being one of the league&rsquo;s most talked about Super Bowl favorites. Denver&rsquo;s offense was good enough last year, but the addition of WR Jaylen Waddle gives the unit a tremendous boost in firepower. The offensive line remains one of the best in football. The defense is the heart and soul of this team, however, as DE Nik Bonitto and former DPOTY CB Pat Surtain II anchor what was the second-overall ranked defense in football last season. Denver should be able to get over the hump and compete for a Lombardi Trophy in 2026."""),
(2, "Los Angeles Chargers", "11-6", "RB Omarion Hampton", """2026 is make it or break it time for the Bolts. Despite being everyone&rsquo;s preseason darling for what feels like the last half-decade, the Chargers have failed to make any real waves into January despite the success of their golden boy QB Justin Herbert. The really fun addition that should actually translate into more offensive success this year is offensive coordinator Mike McDaniel, who has spent most of this preseason ooh&rsquo;ing and aah&rsquo;ing at Herbert&rsquo;s raw ability as a playmaker. C Tyler Biadasz and TE David Njoku highlight the offseason moves, and the defense should remain stout as well under the tutelage of HC Jim Harbaugh. I foresee the Chargers experiencing relative success this season, 10+ wins and a playoff victory don&rsquo;t seem too far out of the realm of possibility"""),
(3, "Kansas City Chiefs", "6-11", "CB Mansoor Delane (R)", """Man, it feels so good to be able to put the Chiefs at third in their division for a second year in a row. I am by no means an overt Kansas City hater, but it just gets boring seeing the same few teams compete year in and year out into February. Luckily for us, the Chiefs&rsquo; dynasty appears to have ended last year after future Hall of Fame QB Patrick Mahomes II finally looked human and was largely unable to capitalize in situations (3rd-and-manageables, red area opportunities) that he has dominated for most of the last decade. TE Travis Kelce returns but should largely be an afterthought. Look for the WR tandem of Rashee Rice and Xavier Worthy to bust some seams, and the addition of 2025&rsquo;s Super Bowl MVP RB Kenneth Walker III to light up the scoreboard for KC. Even if the offense returns to form, the defense has experienced such significant losses in CB&rsquo;s Jaylen Watson and Trent McDuffie Jr both departing for the City of Angels that the Chiefs will again miss the playoffs and be largely non-competitive."""),
(4, "Las Vegas Raiders", "3-14", "LB Nakobe Dean", """After the dismal season that was 2025, the Raiders should actually have a lot to be excited about entering 2026. After spending their first overall draft pick on reigning Heisman winner QB Fernando Mendoza, who led a scrappy Indiana Hoosier team to their first-ever national championship, Raiders fans are very intrigued to see what the future holds. Although Mendoza will likely ride pine behind QB Kirk Cousins (which is, in my opinion, the best thing a team can do for a young, promising quarterback), Vegas&rsquo; offense actually looks kind of dangerous with TE Brock Bowers and RB Ashton Jeanty looking to come into their own in their third and second seasons respectively. The defense added LB Kwity Paye and LB Nakobe Dean in the offseason, who will help this young unit gel alongside elite pass rusher DE Maxx Crosby."""),
]),
("nfc", "North", [
(1, "Detroit Lions", "9-8", "T Blake Miller (R)", """Largely underrated it seems entering 2026 based on a very middling campaign in 2025, the Detroit Lions are still one of the league&rsquo;s elite teams. Although missing out on the playoffs in 2025 with a 9-8 record in a very competitive division definitely hurt, this roster is built more effectively than most other teams in the league and their success in 2026 will reflect that. The offense is loaded. QB Jared Goff has been on a quiet heater over the last few years, with three straight seasons of 4400+ passing yards and 30+ touchdowns. RB Jahmyr Gibbs is the favorite to win Offensive Player of the Year, and WRs Jameson Williams and Amon-Ra St. Brown complement elite pass-catching TE Sam LaPorta. Add in rookie T Blake Miller in tandem with All Pro T Penei Sewell, and it&rsquo;s not that far-fetched to assume Detroit can score 35+ points per game. The defense has more question marks, especially with a few secondary pieces starting on the PUP list, but the return of DE Aidan Hutchinson will make a massive impact on the pass rush and the soul of Dan Campbell&rsquo;s club."""),
(2, "Chicago Bears", "12-5", "DT Kentavius Street", """In 2025, QB Caleb Williams proved himself as a player worthy of the first overall pick in 2024 and then some. Williams provided Chicago with playmaking ability at the quarterback position that the NFL&rsquo;s second-oldest franchise has honestly never seen in its history. Williams led Chicago to a jaw-dropping postseason comeback over the hated Packers, and had Bears fans partying like it was 1985. The Bears&rsquo; success largely runs through if Williams will be able to duplicate and build on the gains he made in HC Ben Johnson&rsquo;s offensive system last year. Holes in the defense will make this more difficult for Caleb and the Bears, but I am drinking the Kool-Aid and I predict Chicago will return to the postseason in 2026."""),
(3, "Green Bay Packers", "9-7-1", "RB MarShawn Lloyd", """Such a strange year for Green Bay in 2025. After looking like 20-0 and a Lombardi homecoming were inevitabilities at the start of the season, the Packers crashed back to earth in spectacular fashion after the loss of LB Micah Parsons and QB Jordan Love. If these two key pieces can stay healthy, Green Bay can certainly make a postseason run, but I just have too many questions about the offensive firepower (even after finally spending their first round pick last year on WR Matthew Golden, the Green and Gold remain without a true WR1). The suspension of RB Josh Jacobs is an off-field scandal that does nothing to help HC Matt LaFleur&rsquo;s team. The defense will have to lean on S Xavier McKinney and LB Zaire Franklin at least through the difficult start of their 2026 schedule as Parsons will begin the year on injured reserve."""),
(4, "Minnesota Vikings", "9-8", "QB Kyler Murray", """It feels like a decade ago when the Vikings won 14 games and made the playoffs. It was actually only two years back, but last year&rsquo;s middling 9-8 campaign led to a lot of people souring on the Purple People Eaters. The experiment with drafting a raw rookie quarterback in JJ McCarthy has been a pretty abject failure, and Minnesota has now turned to the services of veteran QB Kyler Murray to right the ship and get the offense moving back in the right direction. WR Justin Jefferson is still one of the game&rsquo;s elite playmaking receivers, and TE TJ Hockenson should be able to bail Murray out of some 3rd-and-long situations. Minnesota does actually have one of the league&rsquo;s best defenses (7th in scoring last season), but the success of this team will certainly depend on whether Murray is able to replicate the magic of his rookie season seven years later."""),
]),
("nfc", "East", [
(1, "Philadelphia Eagles", "11-6", "WR Makai Lemon (R)", """Rejoice, Eagles faithful, the bad man is gone. After a dominant Super Bowl-winning campaign in 2024, the Eagles crashed spectacularly back to earth last season, a campaign defined largely by the playcalling ineptitude of former offensive coordinator Kevin Patullo. Patullo is out, Sean Mannion is in, and Philly should at least see shades of the 2024 versions of RB Saquon Barkley and QB Jalen Hurts. Hurts will have to rely on the WR tandem of DeVonta Smith and rookie Makai Lemon, as All Pro WR AJ Brown has recently departed for Foxborough. The defense lost a few key pieces in DT Milton Williams, S Reed Blankenship, and LB Nakobe Dean, but the unit is still pretty great and should finish top 10 in defensive rankings."""),
(2, "Dallas Cowboys", "7-9-1", "S Caleb Downs (R)", """Look at me, Cowboys fans. Look me in the eye. It&rsquo;s not your year. The Dallas Cowboys are an enigma. The offense looks primed for another ridiculously successful campaign, boasting a strong running game (RB Javonte Williams), an elite offensive line, one of the best WR corps in the league (CeeDee Lamb and George Pickens), and consistent quarterback play from QB Dak Prescott. The problem with Dallas is that they have the worst defense in football. No amount of moves from owner Jerry Jones last year could salvage what was the worst statistical unit in football. Rookie S Caleb Downs could give Dallas&rsquo; defense the adrenaline shot they need to compete, but my prediction is that Dallas averages 35+ points per game and still misses the playoffs."""),
(3, "New York Giants", "4-13", "LB Arvell Reese (R)", """The New York Giants may actually be competitive in 2026 following a lot of shakeups in the Big Apple, most notably the addition of HC John Harbaugh. Harbaugh will bring a hard-nosed attitude to a team that has done a great job building their roster through the draft over the last few years, and this year under Harbaugh&rsquo;s leadership they may surprise a lot of people. The electric offensive combination of second-year players QB Jaxson Dart and RB Cam Skattebo will continue to hit their stride, with help from the return of elite WR Malik Nabers, whose 2025 campaign was cut short prematurely due to injury. On the other side of the ball, the defensive front seven is legitimately terrifying. Brian Burns, Kayvon Thibodeaux, Abdul Carter, and highly touted Arvell Reese make up a pass-rushing unit that is, on paper, probably the most dangerous in football. If Harbaugh can give this team an identity, the Giants should experience more success than expected in 2026."""),
(4, "Washington Commanders", "5-12", "WR Antonio Williams (R)", """Sigh. After a disaster of a season for Washington in 2025, a campaign marred by injuries all over both sides of the ball, the road back to success just looks more difficult in 2026. QB Jayden Daniels returns to lead the offense alongside WRs Terry McLaurin and newly acquired Stefon Diggs. RB Ja&rsquo;Cory Croskey-Merritt and RB Rachaad White will take some pressure off Daniels in the run game, and barring any more catastrophic injuries (T Laremy Tunsil is already lost for the season), this offense should replicate some of the success of Daniels&rsquo; stellar rookie campaign in 2024. The defense, which was atrocious last year, has plugged some holes in the acquisitions of DE Odafe Oweh and rookie LB Sonny Styles. This unit should likely be better than 2025, again, barring the bite from the injury bug that the team faced in 2025. The problem for Washington isn&rsquo;t necessarily the roster, it is the scheduling start to the year that puts the Commanders in an admittedly terrible position, playing a multitude of road games against some of the league&rsquo;s best teams."""),
]),
("nfc", "South", [
(1, "Tampa Bay Buccaneers", "8-9", "DE Reuben Bain Jr (R)", """Tampa Bay rode the hot hand of QB Baker Mayfield to a blazing start out of the gate last season before crashing back to earth over the second half of the year in a campaign that saw them lose eight of their last eleven games. This team should certainly be better than last year, as a lot of the disaster that was the second half of 2025 can be attributed to injuries. Mayfield will lean on the return of WR Chris Godwin as well as the continued emergence of second year WR Emeka Egbuka. The defense should be top 10 this season, led by elite players S Antoine Winfield Jr and DT Vita Vea, as well as the addition of first round pick DE Reuben Bain Jr. Tampa Bay should win this division handily if all goes according to plan."""),
(2, "Carolina Panthers", "8-9", "WR Jalen Coker", """I believe in QB Bryce Young. Maybe it's his sunny disposition, maybe it&rsquo;s his upbeat attitude, or maybe it&rsquo;s his newfound fiery leadership capabilities, but I foresee Young finally taking the leap that Carolina knew he could make when they selected him with the first overall pick back in 2023. Young finally has playmakers around him, as 2025 first round pick WR Tetairoa McMillan was nothing short of a home run, and WR Jalen Coker continues to come into his own as a very solid WR2. RB Chuba Hubbard will shoulder the load after the departure of 2025 superstar RB Rico Dowdle. The defense last year was right in the middle of the road (16th overall), but should take a massive leap forward with the additions of DE Jaelan Phillips and absurdly underrated LB Devin Lloyd."""),
(3, "New Orleans Saints", "6-11", "DE Chase Young", """A difficult team to predict for 2026. New Orleans was a bottom-dweller last season, but I see the Saints improving significantly this year as second-year QB Tyler Shough builds on the success he saw after taking over the offense towards the end of 2025. Newly acquired RB Travis Etienne will provide a strong boost in the run game, and WR Chris Olave and rookie WR Jordan Tyson (when he returns from injury) will provide Shough with enough firepower to make a legitimate leap forward. The defense was actually sneaky good towards the tail end of 2025, look for former first round pick DE Chase Young to continue the success he enjoyed at the position this season (finished 2025 with 10 sacks in his last 12 games)."""),
(4, "Atlanta Falcons", "8-9", "DT Brandon Dorlus", """Atlanta has a decent roster on paper. A lot of firepower on offense (RB Bijan Robinson, WR Drake London, TE Kyle Pitts), and a defense that looks to be improving a lot over last year with the additions of LBs Azeez Ojulari and Za&rsquo;Darius Smith. CB AJ Terrell is one of the best cover corners in football, and S Jessie Bates III is a potential All Pro at his position as well. The main problem in Atlanta is the most important part of having a successful football team, which is their Quarterbacking Conundrum. After the shocking first round selection of Washington standout QB Michael Penix Jr a few years back, things haven&rsquo;t really panned out for the southpaw. The addition of QB Tua Tagovailoa from Miami further muddies the waters for Atlanta. For this team to have any sort of success in 2026, they need to firmly establish their offensive identity, and fast."""),
]),
("nfc", "West", [
(1, "Los Angeles Rams", "12-5", "TE Terrance Ferguson", """Difficult as it is for me to stomach putting a team that won the Super Bowl at second in their division, HC Sean McVay&rsquo;s Rams are really the first NFL super team that we have seen constructed in this modern era. One of the best offenses in football last year returns reigning MVP QB Matthew Stafford, OPOTY runner up WR Puka Nacua, WR Davante Adams (14 touchdowns in 2025), and elusive RB Kyren Williams. The offense is elite, but the reason the Rams are so heavily favored to win the Super Bowl in 2026 (5-to-1 odds) are the almost comical additions they&rsquo;ve made to their already strong defense. DE Myles Garrett, who won DPOTY last year. CBs Jaylen Watson and Trent McDuffie, both former Super Bowl winners from Kansas City. And, of course, the return from retirement of surefire first-ballot Hall of Famer DT Aaron Donald. The Rams are old. I get it. But this is not a team of the future, this is a team of the now, and as far as rosters go, this is the best team in football."""),
(2, "Seattle Seahawks", "14-3", "RB Jadarian Price (R)", """Wildly underrated as I see it entering the 2026 season, it feels like nobody is really talking about Seattle for a team that firmly cemented themselves as the NFL&rsquo;s best team by winning the Super Bowl last season. Everyone is talking about the Rams and their ridiculous additions, and rightfully so, but the Seahawks seem to strangely be flying under the radar for a team of their calibre. QB Sam Darnold led this group to the promised land in 2025 behind a ridiculously efficient and turnover-avoidant scheme, with help from 2025&rsquo;s OPOTY WR Jaxon Smith-Njigba. WR Rashid Shaheed seems to be making large gains in the offseason as well and should fit in as a more significant part of the offense in 2026. The departure of Super Bowl MVP Kenneth Walker for Kansas City certainly hurts, but the one-two punch of RB Zach Charbonnet (when he returns from injury) and rookie RB Jadarian Price should give Seattle a strong and balanced offense. The defense is elite, led by CB Devon Witherspoon, DT Leonard Williams, and emergent breakout-star candidate DT Byron Murphy. Seattle should absolutely be in contention for a repeat title this year, as it appears the road to glory runs through the best division in football."""),
(3, "San Francisco 49ers", "12-5", "WR De&rsquo;Zhaun Stribling (R)", """For whatever reason, I just don&rsquo;t really believe in the 49ers this season. HC Kyle Shanahan is a great leader, and this team should absolutely be competitive, but I think their division and conference as a whole is just too difficult to really make any noise come playoff time. QB Brock Purdy returns to lead the offense, coupled with All Pro RB Christian McCaffrey and will lean on the new-look receiving corps of WR Mike Evans and rookie WR De&rsquo;Zhaun Stribling. The defense gets a big boost with the arrival of new defensive coordinator Raheem Morris, and the return of LB Fred Warner across LB Dre Greenlaw should see this unit towards the top half of overall rankings come season&rsquo;s end. There&rsquo;s a lot to be excited about in the Bay Area, but the uphill battle is just too steep to climb this year."""),
(4, "Arizona Cardinals", "3-14", "RB Jeremiyah Love (R)", """The Arizona Cardinals are in all-out rebuild mode and should finish towards the bottom of overall league standings in 2026. QB Jacoby Brissett takes the reins as the official starter following a surprisingly efficient 2025 campaign and the departure of franchise stalwart QB Kyler Murray for Minnesota. Third overall pick RB Jeremiyah Love will make an impact early for Arizona, and look for third year WR Marvin Harrison Jr to finally break out now that he has some consistency at the quarterback position. TE Trey McBride is another star piece of this offense, but outside of those names there just isn&rsquo;t enough for the Cardinals to bank on to really expect any sort of success this year. The defense is plain bad (28th overall last season), and doesn't really have any bright spots outside of veteran S Budda Baker and LB Mack Wilson Jr."""),
]),
]


SEEDING = {
"afc": ["Denver Broncos", "Houston Texans", "Buffalo Bills", "Cincinnati Bengals",
        "Los Angeles Chargers", "Baltimore Ravens", "New England Patriots"],
"nfc": ["Los Angeles Rams", "Detroit Lions", "Philadelphia Eagles", "Tampa Bay Buccaneers",
        "Seattle Seahawks", "Chicago Bears", "Carolina Panthers"],
}

AWARDS = [
("Most Valuable Player", ("QB", "Joe Burrow", "Cincinnati Bengals"),
                        ("QB", "Josh Allen", "Buffalo Bills")),
("Offensive Player of the Year", ("RB", "Jahmyr Gibbs", "Detroit Lions"),
                                 ("WR", "Ja&rsquo;Marr Chase", "Cincinnati Bengals")),
("Defensive Player of the Year", ("DE", "Myles Garrett", "Los Angeles Rams"),
                                 ("DE", "Will Anderson Jr", "Houston Texans")),
("Offensive Rookie of the Year", ("WR", "Carnell Tate", "Tennessee Titans"),
                                 ("RB", "Jeremiyah Love", "Arizona Cardinals")),
("Defensive Rookie of the Year", ("LB", "Arvell Reese", "New York Giants"),
                                 ("S", "Caleb Downs", "Dallas Cowboys")),
("Coach of the Year", ("", "DeMeco Ryans", "Houston Texans"),
                      ("", "Sean Payton", "Denver Broncos")),
("Comeback Player of the Year", ("DT", "Aaron Donald", "Los Angeles Rams"),
                                ("QB", "Patrick Mahomes II", "Kansas City Chiefs")),
]
