# 2025-2026 NFL Preseason Report — content verbatim from Adam.
# Each team: (finish, name, 2024 record, breakout candidate, writeup)

LEDE = """It’s that time of year again, and we are officially just over one week from the return of NFL football. After the long, hot summer, the weather will start to cool, the leaves will begin to fall, and Sundays will once again consist of sitting on your couch for 12 hours. Let’s go!"""

DIVISIONS = [
("afc", "North", [
(1, "Baltimore Ravens", "12-5", "CB Nate Wiggins", """The Ravens enter 2025 fresh off of another playoff heartbreaker to the Buffalo Bills, hungry to finally silence the naysayers who recognize their regular season dominance but don’t think they can get over that Super Bowl hump. Following an MVP-caliber season from QB Lamar Jackson, Baltimore returns the majority of their starters and should have no trouble winning the meat grinder that is the AFC North. Look for Jackson to continue to build rapport with third year WR Zay Flowers, as they must depend more on throwing the football this season with future Hall of Fame RB Derrick Henry entering his 10th season."""),
(2, "Cincinnati Bengals", "9-8", "DE Myles Murphy", """After an MVP-level performance from QB Joe Burrow last season, the Bengals return to 2025 with arguably the league’s best offense after resigning WRs Ja’Marr Chase and WR Tee Higgins. The big question for Cincy this year lies on the other side of the ball, where their defense hung the team out to dry time and time again last year, relegating one of the most exciting teams in football to their couches last January. It remains to be seen whether or not the Bengals’ front office did enough in the offseason to address their defense, and if their new-look unit can just be average, Cincinnati should be able to make it to the postseason as a wild card team."""),
(3, "Pittsburgh Steelers", "10-7", "RB Kaleb Johnson (R)", """The Pittsburgh Steelers will look brand-new on offense for 2025, signing veteran signal caller QB Aaron Rodgers after his tumultuous tenure with the New York Jets. After shipping QB Russell Wilson to the Giants, and QB Justin Fields to the Jets, Rodgers will look to build on the strong finish he had to 2024 in what will likely be his last season in the NFL. WR George Pickens and RB Najee Harris are both gone, and the offense will have to rely on the savvy vet’s experience in order to compete in any capacity in one of football’s toughest divisions. The defense will remain stalwart, but it won’t be enough to squeak into the playoffs for Pittsburgh."""),
(4, "Cleveland Browns", "3-14", "QB Joe Flacco", """Football’s most inept organization will trot out the league’s worst team in 2025. Although they did re-sign all-world DE Myles Garrett this offseason, Cleveland has one of the NFL’s worst rosters, and arguably the worst quarterback room in the league. Veteran QB Joe Flacco will likely get the nod to start the season, with rookie signal callers Dillon Gabriel and Shedeur Sanders waiting in the wings. Sanders brings a media circus to Cleveland, although a mediocre showing throughout the preseason will likely relegate him to the bench barring injuries to Cleveland’s other 50 QBs. The Browns have zero expectations this season, although look for WR Jerry Jeudy to build on a strong 2024 campaign as one of the team’s lone bright spots."""),
]),

("afc", "East", [
(1, "Buffalo Bills", "13-4", "WR Keon Coleman", """Another heartbreaking AFC Championship for Buffalo last year, as MVP QB Josh Allen and the Bills were unable to beat the Chiefs on the AFC’s biggest stage once again. In what was supposed to be a “rebuild, reload” year last year, Buffalo dominated throughout the regular season and rode Allen’s MVP season to a deep playoff run. This season, the Bills look primed and ready for another go at the Lombardi, and this will be the year they finally get over the hump and make it to the big game. The AFC East will largely be a cakewalk for the squad this season, and Bills Mafia will be able to defeat Mahomes and Co. in order to advance to their fifth Super Bowl appearance."""),
(2, "New England Patriots", "4-13", "QB Drake Maye", """The New England Patriots are one of the league’s most revamped teams over the offseason, and look like they’ve made all the right moves in order to put their team in a situation to improve significantly this year. New HC Mike Vrabel will guide this team through one of the league’s easiest schedules to the 7th seed in the AFC Playoffs, as New England becomes the league’s most surprising turnaround in 2025. First round pick OL Will Campbell, as well as rookies RB TreVeyon Henderson and WR Kyle Williams will support QB Drake Maye as he makes a huge leap to stardom in year two."""),
(3, "Miami Dolphins", "8-9", "DE Chop Robinson", """Miami has fallen from grace in recent years, going from one of the NFL’s most exciting teams to one of the league’s most middling. Constantly plagued by the injury bug, it will be up to QB Tua Tagovailoa to guide the fast-paced offense back to contention against an average schedule this season. WRs Tyreek Hill and Jaylen Waddle will need to bounce back from mediocre campaigns last year if Miami has any chance of making it to the postseason. The defensive side of the ball has also been lambasted by injuries recently, but if DE Jaelan Phillips can stay healthy and complement future breakout superstar DE Chop Robinson, the Dolphins may be able to turn things around."""),
(4, "New York Jets", "5-12", "WR Arian Smith (R)", """Reports out of training camp this offseason for newly acquired QB Justin Fields have been alarming for Jets fans. New York will enter 2025 as a team that lacks any real sort of identity, as their staunch defensive reputation will be tarnished by key losses on that side of the ball. CB Sauce Gardner will continue his stellar young career with another strong showing, but it won’t be enough to carry a truly atrocious offense through the season. The Jets will field the league’s worst offense in 2025, and will be in contention for the #1 overall pick in the 2026 Draft."""),
]),

("afc", "South", [
(1, "Houston Texans", "10-7", "RB Nick Chubb", """The Texans are in an interesting spot this year, as many are not as high on them following a “sophomore slump” by QB CJ Stroud, a season which still saw Houston win a playoff game. Houston’s front office has done a good job addressing the team’s achilles heel last season, adding key veterans to the offensive line to help protect their star young quarterback. WR Nico Collins, who missed significant time last year with injury, will have a fantastic season this year, and Houston will re-assert themselves as one of the AFC’s true contenders. Featuring one of the league’s strongest defenses, Houston will make a deep playoff run again this season."""),
(2, "Jacksonville Jaguars", "4-13", "WR/CB Travis Hunter (R)", """Jacksonville is a tricky team to nail down for 2025. The Jaguars success this year will rely on how big of a step QB Trevor Lawrence takes in his fifth season, as the highly touted first-overall pick in 2021 hasn’t done anything to propel the Jags to any sort of postseason prosperity. He will need to have a huge year, relying on superstar WR Brian Thomas Jr. in order to have any sort of chance at turning things around in Duval. New HC Liam Coen, who masterminded Tampa Bay’s offensive prowess over the last two seasons, has his hands full with a fairly mediocre roster and will need to really lock in for the Jags to have any sort of success."""),
(3, "Tennessee Titans", "3-14", "QB Cam Ward (R)", """Last year’s bottom dwellers, the Titans believe they have struck gold with first overall pick QB Cam Ward. HC Brian Callahan enters year two of Tennessee’s rebuild with a shiny new toy under center, and although Ward will undoubtedly run into some growing pains, especially early on against some tough defenses, the Titans should be able to improve significantly after the dumpster fire that was 2024. The Titans’ defensive unit was actually pretty good last year, and with the offensive additions of WR Tyler Lockett and WR Van Jefferson, Ward will have a solid veteran receiving corps to rely on."""),
(4, "Indianapolis Colts", "8-9", "DE Kwity Paye", """The Colts rode a tumultuous 8-9 campaign into an even more turbulent offseason, which has recently seen HC Shane Steichen name newly acquired QB Daniel Jones their starter under center. QB Anthony Richardson, Indy’s young project from the 2023 draft, has been historically abysmal for the Colts, and it appears that the franchise is looking to move in a new direction. Daniel Jones will bring little upside to their offense, and although RB Jonathan Taylor will get back on track following a down year in 2024, Jones will not be able to do enough to move the needle in Indianapolis. The defense will improve, but the Colts will be one of the teams competing for pick #1 next April."""),
]),

("afc", "West", [
(1, "Denver Broncos", "10-7", "CB Jahdae Barron (R)", """Yes, you’re reading this correctly. In 2025, the upstart Denver Broncos will dethrone the Kansas City Chiefs to end their streak of winning this division nine times in a row. Denver fans should be ecstatic heading into this new football season, as their second year QB Bo Nix will build on an incredibly strong rookie season. The offense looks improved and ready to take a big step, but the strength of this team will continue to be their staunch defensive unit. DE Nik Bonitto broke out last season, and reigning Defensive Player of the Year Pat Surtain II will continue to dominate in the pass game. Lots of moving and shaking out west."""),
(2, "Kansas City Chiefs", "15-2", "OT Josh Simmons (R)", """Kansas City is still going to make the playoffs, but 2025’s iteration will not resemble the world-beating dynastic teams of the last half-decade. Future Hall of Fame TE Travis Kelce will have other things on his mind this season and age will finally catch up to him, leaving QB Patrick Mahomes II to rely on unproven youngster WR Xavier Worthy following the suspension of WR Rashee Rice. HC Andy Reid is still one of the best in league history, and Kansas City will still be able to practice their black magic in order to earn a berth into the postseason. An early playoff exit seems likely, as one of the most dominant runs in NFL history finally comes to an end."""),
(3, "Los Angeles Chargers", "11-6", "RB Omarion Hampton (R)", """Lots of new faces for HC Jim Harbaugh this season. The Chargers are a strong regular season team led by star QB Justin Herbert, who will be able to lean on the acquisitions of RB Najee Harris and rookie WR Tre Harris. The defense is very strong, but there is just too much competition within this division and the conference at large in order to qualify LA for the postseason. Look for the Chargers to still end up as a double-digit win team, and for second year WR Ladd McConkey to build on a spectacular rookie season in a campaign that just barely falls short again for the Bolts."""),
(4, "Las Vegas Raiders", "4-13", "RB Ashton Jeanty (R)", """Las Vegas is brand new on offense this season, and the defense also looks much improved. Vegas’ front office made the correct decision in paying superstar DE Maxx Crosby, and has also bolstered the unit by adding a plethora of veteran defensive backs and linebackers. The most exciting piece of this team this season will be the emergence of rookie RB Ashton Jeanty. Jeanty had one of the most dominant college seasons by a running back in recent memory last year at Boise State and had a very strong end to the preseason. Newly acquired QB Geno Smith should be able to get cooking quickly with star TE Brock Bowers, and the Raiders should significantly improve to round out one of the league’s strongest divisions."""),
]),

("nfc", "North", [
(1, "Green Bay Packers", "11-6", "WR Matthew Golden (R)", """Green Bay left a lot of meat on the bone last season, but still made the playoffs as a wild card in what was an absolute bloodbath of a division in 2024. Significant regression is sure to come after so much overachieving last year, and this will clear a path for Packers QB Jordan Love to put together his best season to date. The Green and Gold drafted a pass catcher in the first round for this first time in over two decades, and this pick will be an absolute home run as rookie WR Matthew Golden will win Offensive Rookie of the Year as Green Bay sails to the postseason and makes a deep playoff run."""),
(2, "Detroit Lions", "14-3", "WR Isaac TeSlaa (R)", """The perennially snakebitten Lions fell short again last year after spending most of 2024 beating the snot out of their opponents. This team was derailed by injury, specifically on the defensive side of the ball. All-world edge rusher DE Aidan Hutchinson was on a historic pace for QB pressures until his season was ended by a broken leg. He will return to form in 2025, leading a defensive unit that will be one of the strongest in football. On the offensive side, QB Jared Goff will continue to captain the ship effectively, leaning on the league’s best RB tandem of Jahmyr Gibbs and David Montgomery. Add WR Amon-Ra St. Brown, WR Isaac TeSlaa, and TE Sam LaPorta to that equation, and Detroit will continue to be one of the league’s fiercest squads."""),
(3, "Chicago Bears", "5-12", "QB Caleb Williams", """The Detroit Lions’ loss is the Chicago Bears’ gain. Newly hired HC Ben Johnson will shake things up considerably in the Windy City, and second year QB Caleb Williams will show strong improvement, building on a rookie season that had some pretty high highs with some fairly low lows. Bears fans are presumably ready to get hurt again, after the buzz out of Bears camp is sounding better and better by the day. Rookie WR Luther Burden III will complement WR Rome Odunze nicely, but the biggest addition to the offense will be rookie TE Colston Loveland, who was an absolute monster throughout his collegiate career at Michigan. It’s not playoff time just yet in Chicago, but they will certainly be a team to watch out for in the next few years."""),
(4, "Minnesota Vikings", "14-3", "QB JJ McCarthy", """The team with the strongest regression in 2025 will be the Minnesota Vikings, who shocked the league last season by winning 14 games behind their strong defense and strong play of QB Sam Darnold. Darnold earned himself a nice payday out on the West Coast this offseason, so it is now up to second year QB JJ McCarthy to guide the Vikings through this rebuilding period. McCarthy is essentially a rookie, after missing all of 2024 with injury, and Minnesota will experience legitimate growing pains in the league’s toughest division en route to missing the playoffs following a 14 win season."""),
]),

("nfc", "East", [
(1, "Philadelphia Eagles", "14-3", "LB Jihaad Campbell (R)", """Not much to say about Philly here. After one of the most dominating second half runs we’ve seen in recent memory last year, the Eagles basically routed everyone in the playoffs en route to their second Lombardi Trophy. Regression seems unlikely for the defending champs, as they haven’t really lost any significant pieces and had a very strong draft. This team is young and hungry to return to the promised land in 2025. Look for the Birds to return to the big game this season, behind strong campaigns from their offensive big three, QB Jalen Hurts, RB Saquon Barkley, and WR AJ Brown."""),
(2, "Washington Commanders", "12-5", "RB Bill Croskey-Merritt (R)", """The NFL’s biggest surprise last season is ready to defy expectations again this year. Second year QB Jayden Daniels is coming off of the greatest rookie quarterback season we’ve ever seen in a campaign that saw the Commanders go all the way from 4-13 in 2023, to the NFC Championship in 2024. Last year surpassed even Commanders’ fans' wildest dreams, but it doesn’t look like it was one miracle fluke season for the Burgundy and Gold. All-Pro WR Terry McLaurin has a shiny new contract after an offseason hold-in, and the front office has added key pieces to the team like OT Laremy Tunsil and WR Deebo Samuel. The defense will continue to improve, and if Daniels can continue to build on his stellar rookie campaign, the Commanders should be contenders for the next decade plus."""),
(3, "Dallas Cowboys", "7-10", "WR George Pickens", """“It’s our year! It’s our year!” Cowboys fans chant in unison after another season of not winning the Super Bowl. Dallas had an uncharacteristic regular season last year, not even waiting until January to break their fans’ hearts. It should be a better year record-wise for Dallas this season, although offseason turbulence has not been pretty so far for Jerry and Co. All-Pro LB Micah Parsons is still holding out, and the situation between him and Jerry Jones seems irreparable. The offense should look better after adding Steelers WR George Pickens, as this will likely stop teams from double-teaming star WR CeeDee Lamb every down. However, Dallas has once again refused to address their abysmal rushing offense, as well as rushing defense, and this oversight will once again have America’s Team on their couches come playoff time."""),
(4, "New York Giants", "3-14", "QB Jaxson Dart (R)", """The G-Men will likely improve on another dismal 2024 campaign under former Coach of the Year Brian Daboll. The Daniel Jones era is officially over in the Big Apple, and Giants fans can finally rejoice as their quarterback purgatory might just be over after drafting Ole Miss QB Jaxson Dart this offseason. Dart SHOULD NOT start at the beginning of this year, and he should instead sit behind veteran journeyman QB Russell Wilson for the first half of the year before getting handed the keys to the castle. The defense, specifically the defensive line, is actually one of the NFL’s best, and should make life hell for Hurts, Daniels, and Prescott for years to come. WR Malik Nabers should be able to build on a stellar rookie season to cement himself as one of the league’s premier pass catchers."""),
]),

("nfc", "South", [
(1, "Tampa Bay Buccaneers", "10-7", "WR Emeka Egbuka (R)", """Tampa Bay surprised a lot of people last season, boasting one of the league’s most explosive offenses paired with a strong defensive unit. But they didn’t surprise me. QB Baker Mayfield put together an MVP-caliber campaign last season, and he has finally blossomed into one of the league’s best signal callers. Their offense boasts future Hall of Fame WR Mike Evans, WR Chris Godwin, who is coming off of a down 2024 but should bounce back this year, second year RB Bucky Irving, who took the league by storm last season, and rookie WR Emeka Egbuka, who the Bucs took in the top ten of the draft and should provide Mayfield with another strong target. Tampa Bay continues their NFC South dominance in 2025 en route to their fifth straight division title."""),
(2, "Carolina Panthers", "5-12", "QB Bryce Young", """Maybe a surprising pick to rank the Panthers ahead of their division rival Atlanta Falcons, but there were too many good things I saw out of Carolina in the second half of last year. After QB Bryce Young was benched for a few weeks for vet QB Andy Dalton, Young returned to the lineup and played admirably, living up to the hype that he had as 2023’s first overall pick. WR Xavier Legette should be much improved, and the Panthers’ front office has made a number of offseason moves to address their atrocious defense in order to help support their young team. It’s not playoff time just yet in Charlotte, but this team could be a problem over the next half decade."""),
(3, "Atlanta Falcons", "8-9", "QB Michael Penix Jr.", """Atlanta is a bit of an enigma for me this season. Their success hinges on the emergence of their second year QB Michael Penix Jr., who played fairly well in only three appearances last season. The jury is out on Penix, but he does have a strong offensive line and the ability to rely on fantastic offensive weapons WR Drake London (barring injury) and RB Bijan Robinson. The offense should be good, but the defense is what will drag the team down in 2024. Playing a relatively weak schedule will help Atlanta, but the up-and-down play of unproven Michael Penix Jr. will have the Dirty Birds missing out on the postseason yet again."""),
(4, "New Orleans Saints", "3-14", "QB Spencer Rattler", """Unfortunately for the New Orleans faithful, the Saints are in full rebuild mode following a disastrous 2024 campaign. A quarterback battle will occur throughout 2025, where rookie QB Tyler Shough will be waiting in the wings for starting QB Spencer Rattler to misfire. Rattler actually looked decent through the second half of 2024, and has a lot to build on throughout this upcoming season. The defense is a disaster, and will not be able to get off the field to allow Rattler, RB Alvin Kamara, and WR Chris Olave to make any meaningful contributions to the scoreboard this year. Look for the Saints to compete for the #1 overall pick in April."""),
]),

("nfc", "West", [
(1, "Seattle Seahawks", "10-7", "TE Elijah Arroyo (R)", """Okay, okay, hear me out. Last season, QB Sam Darnold relied on a strong defense and a superstar wide receiver to guide the Minnesota Vikings to a 14 win season. What does Darnold inherit in Seattle? An excellent young defense, and an emerging superstar in WR Jaxon Smith-Njigba. Second year HC Mike Macdonald took a ragtag group to the brink of playoff contention last year, and after overachieving last year with QB Geno Smith, Seattle will ride the more conservative play style of Darnold to their first division title in years. The strength of this team is certainly their defensive unit, but their offense will surprise people this season."""),
(2, "Los Angeles Rams", "10-7", "DE Braden Fiske", """A lot of people are very high on the Rams going into 2025, and their success this year will be contingent on the strength of QB Matthew Stafford’s back. If it holds up throughout the year, Stafford has a very strong offense to pilot, and the addition of WR Davante Adams should lead the Rams to the playoffs. However, Stafford is 37 years old, and back injuries are generally not things that simply vanish. Without Stafford, this offense will struggle. Mightily. Luckily, Los Angeles boasts one of the league’s best defensive fronts, and DE Jared Verse will build on his Defensive Rookie of the Year campaign en route to being in contention for Defensive Player of the Year. Verse is a fitting heir to Aaron Donald’s throne, but don’t sleep on their second year DE on the other side, Braden Fiske."""),
(3, "San Francisco 49ers", "6-11", "WR Ricky Pearsall", """I just don’t believe in San Francisco going into 2025. Although they have one of the easiest schedule in the league this year, the team did not do enough to mitigate their injury issues last year to show me that their Super Bowl window hasn’t slammed shut. Departures of S Talanoa Hufanga and WR Deebo Samuel will hurt the team, and although RB Christian McCaffrey returns to the lineup, it won’t be enough to address the lingering injury concerns with most of the roster heading into this season. QB Brock Purdy is not enough of a game breaker to put the team on his back, and San Francisco will follow 2024’s disappointment with another year of missing the postseason."""),
(4, "Arizona Cardinals", "8-9", "WR Marvin Harrison Jr.", """Arizona is another perplexing team going into the new season next week. QB Kyler Murray enters his seventh pro season, and the former Heisman winner and #1 overall pick has never returned to the highs of his stellar rookie campaign all those years ago. He is inconsistent, and not a quarterback who can sustain a deep postseason run regardless of the offense around him. This offense is not particularly strong either, outside of WR Marvin Harrison Jr, who should improve on a relatively strong rookie campaign, and TE Trey McBride, who should likely be a Pro Bowler this season. Arizona misses the playoffs again behind another underwhelming campaign from Murray, and a fairly weak defensive unit."""),
]),
]

SEEDING = {
"afc": ["Buffalo Bills", "Baltimore Ravens", "Houston Texans", "Denver Broncos",
        "Kansas City Chiefs", "Cincinnati Bengals", "New England Patriots"],
"nfc": ["Philadelphia Eagles", "Green Bay Packers", "Tampa Bay Buccaneers", "Seattle Seahawks",
        "Washington Commanders", "Detroit Lions", "Los Angeles Rams"],
}

AWARDS = [
("NFL MVP", ("QB", "Lamar Jackson", "Baltimore Ravens")),
("Offensive Player of the Year", ("WR", "Ja’Marr Chase", "Cincinnati Bengals")),
("Defensive Player of the Year", ("CB", "Derek Stingley Jr", "Houston Texans")),
("Offensive Rookie of the Year", ("WR", "Matthew Golden", "Green Bay Packers")),
("Defensive Rookie of the Year", ("CB", "Jahdae Barron", "Denver Broncos")),
("Coach of the Year", ("", "Mike Vrabel", "New England Patriots")),
("Comeback Player of the Year", ("DE", "Aidan Hutchinson", "Detroit Lions")),
]
